{
  "NServiceBus.MessageId": "c87fd110-d03e-4b40-ba2b-a85d0115d92f",
  "NServiceBus.MessageIntent": "Reply",
  "NServiceBus.ReplyToAddress": "Samples.Mvc.Server",
  "NServiceBus.CorrelationId": "30111319-c913-4a36-8016-a85d01154d01",
  "NServiceBus.OriginatingMachine": "CLN10907",
  "NServiceBus.OriginatingEndpoint": "Samples.Mvc.Server",
  "$.diagnostics.originating.hostid": "455a786552e4de8d5c304a747891df30",
  "NServiceBus.ContentType": "text\/xml",
  "NServiceBus.EnclosedMessageTypes": "NBusShared.Response.GetCarsResponse, NBusShared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
  "NServiceBus.RelatedTo": "30111319-c913-4a36-8016-a85d01154d01",
  "NServiceBus.ConversationId": "85a95509-c2d9-4f19-bc26-a85d01154d25",
  "NServiceBus.Version": "6.4.3",
  "NServiceBus.TimeSent": "2018-01-03 16:51:36:947464 Z",
  "NServiceBus.ExceptionInfo.ExceptionType": "System.InvalidOperationException",
  "NServiceBus.Retries.Timestamp": "2018-01-03 17:04:08:478286 Z",
  "NServiceBus.ExceptionInfo.HelpLink": null,
  "NServiceBus.ExceptionInfo.Message": "No handlers could be found for message type: NBusShared.Response.GetCarsResponse",
  "NServiceBus.ExceptionInfo.Source": "NServiceBus.Core",
  "NServiceBus.ExceptionInfo.StackTrace": "System.InvalidOperationException: No handlers could be found for message type: NBusShared.Response.GetCarsResponse\u000d\u000a   vid NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext() i C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Pipeline\\Incoming\\LoadHandlersConnector.cs:rad 31\u000d\u000a--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\u000d\u000a   vid NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext() i C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Pipeline\\Incoming\\DeserializeLogicalMessagesConnector.cs:rad 33\u000d\u000a--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\u000d\u000a   vid NServiceBus.ReceivePerformanceDiagnosticsBehavior.<Invoke>d__2.MoveNext() i C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Performance\\Statistics\\ReceivePerformanceDiagnosticsBehavior.cs:rad 40\u000d\u000a--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\u000d\u000a   vid NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext() i C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Performance\\Statistics\\ProcessingStatisticsBehavior.cs:rad 27\u000d\u000a--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\u000d\u000a   vid NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext() i C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Pipeline\\Incoming\\TransportReceiveToPhysicalMessageProcessingConnector.cs:rad 37\u000d\u000a--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\u000d\u000a   vid NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext() i C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Pipeline\\MainPipelineExecutor.cs:rad 32\u000d\u000a--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\u000d\u000a   vid NServiceBus.LearningTransportMessagePump.<ProcessFile>d__9.MoveNext() i C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Transports\\Learning\\LearningTransportMessagePump.cs:rad 277",
  "NServiceBus.TimeOfFailure": "2018-01-03 17:24:00:390458 Z",
  "NServiceBus.FailedQ": "Samples.Mvc.WebApplication-1",
  "NServiceBus.ProcessingMachine": "CLN10907",
  "NServiceBus.ProcessingEndpoint": "Samples.Mvc.WebApplication",
  "$.diagnostics.hostid": "4e4036b1be04d1fc58b6a96fdac95d49",
  "$.diagnostics.hostdisplayname": "CLN10907"
}